name: build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Zig
        uses: mlugg/setup-zig@v1
        with:
          version: master

      - name: Setup Emscripten
        uses: mymindstorm/setup-emsdk@v14

      - name: Cache emscripten
        uses: actions/cache@v4
        with:
          path: ~/.emscripten_cache
          key: emsdk-${{ runner.os }}

      - name: Build WASM (Release)
        run: |
          zig build -Dtarget=wasm32-emscripten \
                    -Doptimize=ReleaseFast \
                    --sysroot "$(em-config CACHE)/sysroot"

      - name: Copy index.html
        run: |
          mkdir -p zig-out/www
          cp index.html zig-out/www/index.html

      - name: Upload artifact (web)
        uses: actions/upload-artifact@v4
        with:
          name: wrumz-web
          path: zig-out/www

      - name: Build native (Release)
        run: zig build -Doptimize=ReleaseFast

      - name: Upload native binary
        uses: actions/upload-artifact@v4
        with:
          name: wrumz-native
          path: zig-out/bin
